services:
  cleanarchitecturetemplate.api:
    image: ${DOCKER_REGISTRY-}cleanarchitecturetemplate.api
    container_name: cleanarchitecturetemplate.api
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/CleanArchitectureTemplate.Api/Dockerfile
    ports:
      - 5000:8080
    networks:
      - cleanarchitecturetemplate-bridge

  cleanarchitecturetemplate.mysql:
    image: mysql:8.4.0
    container_name: cleanarchitecturetemplate.mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cleanarchitecturetemplate
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cleanarchitecturetemplate-bridge
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 5
      interval: 5s
      timeout: 30s

volumes:
  mysql-data:

networks:
  cleanarchitecturetemplate-bridge:
    driver: bridge
